debug: true
app: tool-agent
server:
  addr: ":8080"
log:
  development: true
  level: debug
  disable_sentry: true
  outputs:
    - stdout
    - ./logs/tool-agent.log
# 数据库配置
tools:
  dialect: mysql
  dsn: root:123456@tcp(127.0.0.1:3307)/tool-agent?charset=utf8mb4&parseTime=True&loc=Local
# 定时任务配置
demo:
  cron: "*/1 * * * *"
