// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wechat-tools/model"
)

func newSPictureBook(db *gorm.DB, opts ...gen.DOOption) sPictureBook {
	_sPictureBook := sPictureBook{}

	_sPictureBook.sPictureBookDo.UseDB(db, opts...)
	_sPictureBook.sPictureBookDo.UseModel(&model.SPictureBook{})

	tableName := _sPictureBook.sPictureBookDo.TableName()
	_sPictureBook.ALL = field.NewAsterisk(tableName)
	_sPictureBook.Id = field.NewUint64(tableName, "id")
	_sPictureBook.BookId = field.NewString(tableName, "book_id")
	_sPictureBook.Title = field.NewString(tableName, "title")
	_sPictureBook.Icon = field.NewString(tableName, "icon")
	_sPictureBook.CategoryId = field.NewString(tableName, "category_id")
	_sPictureBook.Type = field.NewInt(tableName, "type")
	_sPictureBook.Status = field.NewString(tableName, "status")
	_sPictureBook.Position = field.NewInt(tableName, "position")
	_sPictureBook.CreatedAt = field.NewTime(tableName, "created_at")
	_sPictureBook.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sPictureBook.DeletedAt = field.NewField(tableName, "deleted_at")

	_sPictureBook.fillFieldMap()

	return _sPictureBook
}

type sPictureBook struct {
	sPictureBookDo

	ALL        field.Asterisk
	Id         field.Uint64 // 主键
	BookId     field.String // 绘本id
	Title      field.String // 绘本标题
	Icon       field.String // 绘本封面
	CategoryId field.String // 绘本所属栏目
	Type       field.Int    // 1中文绘本,2英文绘本,3古诗绘本,4英语词汇
	Status     field.String // 状态,on启用,off禁用
	Position   field.Int    // 排序位置
	CreatedAt  field.Time   // 添加时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s sPictureBook) Table(newTableName string) *sPictureBook {
	s.sPictureBookDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sPictureBook) As(alias string) *sPictureBook {
	s.sPictureBookDo.DO = *(s.sPictureBookDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sPictureBook) updateTableName(table string) *sPictureBook {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint64(table, "id")
	s.BookId = field.NewString(table, "book_id")
	s.Title = field.NewString(table, "title")
	s.Icon = field.NewString(table, "icon")
	s.CategoryId = field.NewString(table, "category_id")
	s.Type = field.NewInt(table, "type")
	s.Status = field.NewString(table, "status")
	s.Position = field.NewInt(table, "position")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sPictureBook) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sPictureBook) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.Id
	s.fieldMap["book_id"] = s.BookId
	s.fieldMap["title"] = s.Title
	s.fieldMap["icon"] = s.Icon
	s.fieldMap["category_id"] = s.CategoryId
	s.fieldMap["type"] = s.Type
	s.fieldMap["status"] = s.Status
	s.fieldMap["position"] = s.Position
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sPictureBook) clone(db *gorm.DB) sPictureBook {
	s.sPictureBookDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sPictureBook) replaceDB(db *gorm.DB) sPictureBook {
	s.sPictureBookDo.ReplaceDB(db)
	return s
}

type sPictureBookDo struct{ gen.DO }

type ISPictureBookDo interface {
	gen.SubQuery
	Debug() ISPictureBookDo
	WithContext(ctx context.Context) ISPictureBookDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISPictureBookDo
	WriteDB() ISPictureBookDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISPictureBookDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISPictureBookDo
	Not(conds ...gen.Condition) ISPictureBookDo
	Or(conds ...gen.Condition) ISPictureBookDo
	Select(conds ...field.Expr) ISPictureBookDo
	Where(conds ...gen.Condition) ISPictureBookDo
	Order(conds ...field.Expr) ISPictureBookDo
	Distinct(cols ...field.Expr) ISPictureBookDo
	Omit(cols ...field.Expr) ISPictureBookDo
	Join(table schema.Tabler, on ...field.Expr) ISPictureBookDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureBookDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISPictureBookDo
	Group(cols ...field.Expr) ISPictureBookDo
	Having(conds ...gen.Condition) ISPictureBookDo
	Limit(limit int) ISPictureBookDo
	Offset(offset int) ISPictureBookDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureBookDo
	Unscoped() ISPictureBookDo
	Create(values ...*model.SPictureBook) error
	CreateInBatches(values []*model.SPictureBook, batchSize int) error
	Save(values ...*model.SPictureBook) error
	First() (*model.SPictureBook, error)
	Take() (*model.SPictureBook, error)
	Last() (*model.SPictureBook, error)
	Find() ([]*model.SPictureBook, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureBook, err error)
	FindInBatches(result *[]*model.SPictureBook, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SPictureBook) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISPictureBookDo
	Assign(attrs ...field.AssignExpr) ISPictureBookDo
	Joins(fields ...field.RelationField) ISPictureBookDo
	Preload(fields ...field.RelationField) ISPictureBookDo
	FirstOrInit() (*model.SPictureBook, error)
	FirstOrCreate() (*model.SPictureBook, error)
	FindByPage(offset int, limit int) (result []*model.SPictureBook, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISPictureBookDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sPictureBookDo) Debug() ISPictureBookDo {
	return s.withDO(s.DO.Debug())
}

func (s sPictureBookDo) WithContext(ctx context.Context) ISPictureBookDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sPictureBookDo) ReadDB() ISPictureBookDo {
	return s.Clauses(dbresolver.Read)
}

func (s sPictureBookDo) WriteDB() ISPictureBookDo {
	return s.Clauses(dbresolver.Write)
}

func (s sPictureBookDo) Session(config *gorm.Session) ISPictureBookDo {
	return s.withDO(s.DO.Session(config))
}

func (s sPictureBookDo) Clauses(conds ...clause.Expression) ISPictureBookDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sPictureBookDo) Returning(value interface{}, columns ...string) ISPictureBookDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sPictureBookDo) Not(conds ...gen.Condition) ISPictureBookDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sPictureBookDo) Or(conds ...gen.Condition) ISPictureBookDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sPictureBookDo) Select(conds ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sPictureBookDo) Where(conds ...gen.Condition) ISPictureBookDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sPictureBookDo) Order(conds ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sPictureBookDo) Distinct(cols ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sPictureBookDo) Omit(cols ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sPictureBookDo) Join(table schema.Tabler, on ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sPictureBookDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sPictureBookDo) RightJoin(table schema.Tabler, on ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sPictureBookDo) Group(cols ...field.Expr) ISPictureBookDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sPictureBookDo) Having(conds ...gen.Condition) ISPictureBookDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sPictureBookDo) Limit(limit int) ISPictureBookDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sPictureBookDo) Offset(offset int) ISPictureBookDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sPictureBookDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISPictureBookDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sPictureBookDo) Unscoped() ISPictureBookDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sPictureBookDo) Create(values ...*model.SPictureBook) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sPictureBookDo) CreateInBatches(values []*model.SPictureBook, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sPictureBookDo) Save(values ...*model.SPictureBook) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sPictureBookDo) First() (*model.SPictureBook, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBook), nil
	}
}

func (s sPictureBookDo) Take() (*model.SPictureBook, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBook), nil
	}
}

func (s sPictureBookDo) Last() (*model.SPictureBook, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBook), nil
	}
}

func (s sPictureBookDo) Find() ([]*model.SPictureBook, error) {
	result, err := s.DO.Find()
	return result.([]*model.SPictureBook), err
}

func (s sPictureBookDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SPictureBook, err error) {
	buf := make([]*model.SPictureBook, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sPictureBookDo) FindInBatches(result *[]*model.SPictureBook, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sPictureBookDo) Attrs(attrs ...field.AssignExpr) ISPictureBookDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sPictureBookDo) Assign(attrs ...field.AssignExpr) ISPictureBookDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sPictureBookDo) Joins(fields ...field.RelationField) ISPictureBookDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sPictureBookDo) Preload(fields ...field.RelationField) ISPictureBookDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sPictureBookDo) FirstOrInit() (*model.SPictureBook, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBook), nil
	}
}

func (s sPictureBookDo) FirstOrCreate() (*model.SPictureBook, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SPictureBook), nil
	}
}

func (s sPictureBookDo) FindByPage(offset int, limit int) (result []*model.SPictureBook, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sPictureBookDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sPictureBookDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sPictureBookDo) Delete(models ...*model.SPictureBook) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sPictureBookDo) withDO(do gen.Dao) *sPictureBookDo {
	s.DO = *do.(*gen.DO)
	return s
}
