// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"wechat-tools/model"
)

func newSWechatUser(db *gorm.DB, opts ...gen.DOOption) sWechatUser {
	_sWechatUser := sWechatUser{}

	_sWechatUser.sWechatUserDo.UseDB(db, opts...)
	_sWechatUser.sWechatUserDo.UseModel(&model.SWechatUser{})

	tableName := _sWechatUser.sWechatUserDo.TableName()
	_sWechatUser.ALL = field.NewAsterisk(tableName)
	_sWechatUser.Id = field.NewUint64(tableName, "id")
	_sWechatUser.UserName = field.NewString(tableName, "user_name")
	_sWechatUser.Score = field.NewInt(tableName, "score")
	_sWechatUser.CreatedAt = field.NewTime(tableName, "created_at")
	_sWechatUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sWechatUser.DeletedAt = field.NewField(tableName, "deleted_at")

	_sWechatUser.fillFieldMap()

	return _sWechatUser
}

type sWechatUser struct {
	sWechatUserDo

	ALL       field.Asterisk
	Id        field.Uint64 // 主键
	UserName  field.String // 用户名
	Score     field.Int    // 分值
	CreatedAt field.Time   // 添加时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s sWechatUser) Table(newTableName string) *sWechatUser {
	s.sWechatUserDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sWechatUser) As(alias string) *sWechatUser {
	s.sWechatUserDo.DO = *(s.sWechatUserDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sWechatUser) updateTableName(table string) *sWechatUser {
	s.ALL = field.NewAsterisk(table)
	s.Id = field.NewUint64(table, "id")
	s.UserName = field.NewString(table, "user_name")
	s.Score = field.NewInt(table, "score")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sWechatUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sWechatUser) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.Id
	s.fieldMap["user_name"] = s.UserName
	s.fieldMap["score"] = s.Score
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sWechatUser) clone(db *gorm.DB) sWechatUser {
	s.sWechatUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sWechatUser) replaceDB(db *gorm.DB) sWechatUser {
	s.sWechatUserDo.ReplaceDB(db)
	return s
}

type sWechatUserDo struct{ gen.DO }

type ISWechatUserDo interface {
	gen.SubQuery
	Debug() ISWechatUserDo
	WithContext(ctx context.Context) ISWechatUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISWechatUserDo
	WriteDB() ISWechatUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISWechatUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISWechatUserDo
	Not(conds ...gen.Condition) ISWechatUserDo
	Or(conds ...gen.Condition) ISWechatUserDo
	Select(conds ...field.Expr) ISWechatUserDo
	Where(conds ...gen.Condition) ISWechatUserDo
	Order(conds ...field.Expr) ISWechatUserDo
	Distinct(cols ...field.Expr) ISWechatUserDo
	Omit(cols ...field.Expr) ISWechatUserDo
	Join(table schema.Tabler, on ...field.Expr) ISWechatUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISWechatUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISWechatUserDo
	Group(cols ...field.Expr) ISWechatUserDo
	Having(conds ...gen.Condition) ISWechatUserDo
	Limit(limit int) ISWechatUserDo
	Offset(offset int) ISWechatUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISWechatUserDo
	Unscoped() ISWechatUserDo
	Create(values ...*model.SWechatUser) error
	CreateInBatches(values []*model.SWechatUser, batchSize int) error
	Save(values ...*model.SWechatUser) error
	First() (*model.SWechatUser, error)
	Take() (*model.SWechatUser, error)
	Last() (*model.SWechatUser, error)
	Find() ([]*model.SWechatUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SWechatUser, err error)
	FindInBatches(result *[]*model.SWechatUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SWechatUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISWechatUserDo
	Assign(attrs ...field.AssignExpr) ISWechatUserDo
	Joins(fields ...field.RelationField) ISWechatUserDo
	Preload(fields ...field.RelationField) ISWechatUserDo
	FirstOrInit() (*model.SWechatUser, error)
	FirstOrCreate() (*model.SWechatUser, error)
	FindByPage(offset int, limit int) (result []*model.SWechatUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISWechatUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sWechatUserDo) Debug() ISWechatUserDo {
	return s.withDO(s.DO.Debug())
}

func (s sWechatUserDo) WithContext(ctx context.Context) ISWechatUserDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sWechatUserDo) ReadDB() ISWechatUserDo {
	return s.Clauses(dbresolver.Read)
}

func (s sWechatUserDo) WriteDB() ISWechatUserDo {
	return s.Clauses(dbresolver.Write)
}

func (s sWechatUserDo) Session(config *gorm.Session) ISWechatUserDo {
	return s.withDO(s.DO.Session(config))
}

func (s sWechatUserDo) Clauses(conds ...clause.Expression) ISWechatUserDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sWechatUserDo) Returning(value interface{}, columns ...string) ISWechatUserDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sWechatUserDo) Not(conds ...gen.Condition) ISWechatUserDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sWechatUserDo) Or(conds ...gen.Condition) ISWechatUserDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sWechatUserDo) Select(conds ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sWechatUserDo) Where(conds ...gen.Condition) ISWechatUserDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sWechatUserDo) Order(conds ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sWechatUserDo) Distinct(cols ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sWechatUserDo) Omit(cols ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sWechatUserDo) Join(table schema.Tabler, on ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sWechatUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sWechatUserDo) RightJoin(table schema.Tabler, on ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sWechatUserDo) Group(cols ...field.Expr) ISWechatUserDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sWechatUserDo) Having(conds ...gen.Condition) ISWechatUserDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sWechatUserDo) Limit(limit int) ISWechatUserDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sWechatUserDo) Offset(offset int) ISWechatUserDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sWechatUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISWechatUserDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sWechatUserDo) Unscoped() ISWechatUserDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sWechatUserDo) Create(values ...*model.SWechatUser) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sWechatUserDo) CreateInBatches(values []*model.SWechatUser, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sWechatUserDo) Save(values ...*model.SWechatUser) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sWechatUserDo) First() (*model.SWechatUser, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SWechatUser), nil
	}
}

func (s sWechatUserDo) Take() (*model.SWechatUser, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SWechatUser), nil
	}
}

func (s sWechatUserDo) Last() (*model.SWechatUser, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SWechatUser), nil
	}
}

func (s sWechatUserDo) Find() ([]*model.SWechatUser, error) {
	result, err := s.DO.Find()
	return result.([]*model.SWechatUser), err
}

func (s sWechatUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SWechatUser, err error) {
	buf := make([]*model.SWechatUser, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sWechatUserDo) FindInBatches(result *[]*model.SWechatUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sWechatUserDo) Attrs(attrs ...field.AssignExpr) ISWechatUserDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sWechatUserDo) Assign(attrs ...field.AssignExpr) ISWechatUserDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sWechatUserDo) Joins(fields ...field.RelationField) ISWechatUserDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sWechatUserDo) Preload(fields ...field.RelationField) ISWechatUserDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sWechatUserDo) FirstOrInit() (*model.SWechatUser, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SWechatUser), nil
	}
}

func (s sWechatUserDo) FirstOrCreate() (*model.SWechatUser, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SWechatUser), nil
	}
}

func (s sWechatUserDo) FindByPage(offset int, limit int) (result []*model.SWechatUser, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sWechatUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sWechatUserDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sWechatUserDo) Delete(models ...*model.SWechatUser) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sWechatUserDo) withDO(do gen.Dao) *sWechatUserDo {
	s.DO = *do.(*gen.DO)
	return s
}
